apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: devtools
  labels:
    name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command: 
    - /busybox/echo hola mundo
    tty: true
  restartPolicy: Never